version: 2
jobs:
  build:
    working_directory: ~/python-ci
    docker:
      - image: circleci/python:3.6.4 
    steps:
      - checkout  # checkout source code to working directory
      - python/install-deps
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
          name: Install PyEnv
      - run:
          command: |
            nosetests tests/math-test.py
          name: Test

