version: 2
jobs:
  build:
    working_directory: ~/python-ci
    docker:
      - image: circleci/python:3.6.4 
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
          name: Install PyEnv
      - run:
          command: |
            if true; then
              pip install --user -r requirements.txt
            else
              pip install -r requirements.txt
            fi
          name: Install dependencies 
workflows:
  install-dependencies:
    jobs:
      - build:
          name: Install dependencies
          filters:
            branches:
              only:
                - main
                - development
